### ISSUE TITLE
A couple typos

### ISSUE THREAD

**Issue by bvssvni** [kvark/gfx_scene#17]
This line needs a `//!` https://github.com/kvark/gfx_scene/blob/master/src/phase/lib.rs#L4

"instancing" https://github.com/kvark/gfx_scene/blob/master/src/phase/lib.rs#L33

**Comment by bvssvni** [comment]
"updated" https://github.com/kvark/gfx_scene/blob/master/src/phase/lib.rs#L52

**Comment by kvark** [comment]
Thanks!

**Comment by bvssvni** [comment]
Found an extra indent https://github.com/kvark/gfx_scene/blob/master/src/phase/mem.rs#L21
